server:
  port: 8080

spring:
  application:
    name: prime-secure-bank
  
  datasource:
    url: jdbc:mysql://localhost:3306/prime_bank_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "" # Make sure to update if root has a password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates the tables based on entities
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# Custom Application Properties
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expirationMs: 86400000 # 24 hours
